version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_stree
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: garita
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - stree_network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_stree
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - stree_network

networks:
  stree_network:
    driver: bridge
